version: '3.0'
services:
  # website:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "10000:80"
  #   volumes:
  #     - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./frontend/dist:/website
  #   depends_on:
  #     - api-server
  #   links:
  #     - api-server
  #   network_mode: bridge
  website:
    build: ./frontend
    ports:
      - "10000:80"
    links:
      - api-server
    depends_on:
      - api-server
    network_mode: bridge
    command: ['nginx', '-g', 'daemon off;']

  # mobile-website:
  #   image: nginx:alpine
  #   restart: always
  #   ports:
  #     - "10001:80"
  #   volumes:
  #     - ./mobile/config/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./mobile/dist:/website
  #   depends_on:
  #     - api-server
  #   links:
  #     - api-server
  #   network_mode: bridge
      
  api-server:
    build: ./api-server
    # restart: always
    volumes:
      - /srv/cailab-homepage/db:/app/db
    network_mode: bridge
